---
name: CI - YAMLLINT

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements-py/requirements-py-dev.txt

      - name: Install dependencies.
        run: pip3 install -r requirements-py/requirements-py-dev.txt

      - name: Lint code.
        run: |
          yamllint .
